### PR TITLE
Week 2 Progress: Thenaesh Elango

### PR DESCRIPTION
**Pull request by thenaesh**

### CODE REVIEW

**Comment by damithc** [comment]
Squash?

**Comment by damithc** [comment]
Actually I think the unsightly list of commits come from your previous PR. The reason is your master branch is not clean. Do a proper sync of the master branch after this PR is merged.

**Comment by thenaesh** [comment]
The mess came from me creating a new branch from the old one instead of from master. Fixing now.

**Comment by thenaesh** [comment]
Ok, cleaned up the mess. :)

**Pull request merged**
