### PR TITLE
Fix relative links for external sites

### LINKED ISSUE #25: Some external links are using relative paths
Currently, some of the eternal links are relative links, resulting in a 404.

E.g. `external.com` goes to `https://nus-oss.github.io/cs3281-website/students/AY1617S2/external.com`. The correct link should be `http://external.com`.

### PR DESCRIPTION
**Pull request by li-kai**
Fixes #25.

### CODE REVIEW

**Comment by damithc** [comment]
Thanks @li-kai

**Comment by damithc** [comment]
I'm getting a generic github page build failure after this commit, not sure why though.

```
The page build failed with the following error:

Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds
```

**Comment by damithc** [comment]
> I'm getting a generic github page build failure after this commit, not sure why though.

@li-kai Seems to be an intermittent problem on GitHub pages. It didn't occur on subsequent commits.

**Comment by li-kai** [comment]
@damithc Glad to know 👍

**Pull request merged**
