### PR TITLE
Week 3 Progress: Ch'ng Ming Shin

### PR DESCRIPTION
**Pull request by ablyx**

### CODE REVIEW

**Comment by damithc** [comment]
@ablyx As an exercise in Git, try to clean up your master branch so that no unrelated commits appear in the PR. :-)

**Comment by ablyx** [comment]
@damithc I messed up so I did a very hard reset... But I used fixup to clean them up the unrelated commits. Do I always have to use fixup whenever I pull from upstream?

**Comment by damithc** [comment]
> Do I always have to use fixup whenever I pull from upstream?

Usually no. This only happens if you use master branch to submit PRs, which we no longer do. After this PR is merged, do a hard reset of your fork. Next semester, I plan to require branching from the beginning so that this situation can be avoided altogether.

**Comment by ablyx** [comment]
ok done!

**Pull request merged**
